import type { CodingCompetencyKey } from "./coding-developer";

export type PublicCodingInterviewPrompt = {
  id: string;
  title: string;
  durationMinutes: number;
  prompt: string;
  mode: "architecture" | "debug" | "ai-boundary" | "project-defense" | "requirements-change";
  guidedHint: string;
  followUp: string;
  competencyWeights: Partial<Record<CodingCompetencyKey, number>>;
};

/** Learner-facing prompt projection. Private rubric requirements remain on the server. */
export const codingInterviewPrompts: PublicCodingInterviewPrompt[] = [
  { id: "interview-overdue-tasks", title: "30-minute overdue-task utility", durationMinutes: 30, mode: "architecture", prompt: "Build a small Python program that reads fictional team tasks and identifies overdue items. Explain the data shape, deterministic rule, tests, and why AI is not part of this first version.", guidedHint: "Start with a list of task dictionaries, a clear due-date comparison, and a small test set. State why a probabilistic model would add no value to an explicit date rule.", followUp: "A user wants the output sorted by accountable owner. What small change would you make, and what would you test?", competencyWeights: { python: .8, decomposition: 1, dataInterfaces: .8, testingDebugging: .7, defense: .8 } },
  { id: "interview-sensor-limits", title: "45-minute sensor-limits API", durationMinutes: 45, mode: "architecture", prompt: "Build a typed API that accepts fictional sensor readings and returns the readings outside configured limits. Explain the contract, configuration boundary, response, error behavior, and focused tests.", guidedHint: "Describe the request model, a pure comparison function, a configured limit source, invalid-input behavior, and an exact-boundary test before discussing extra features.", followUp: "The limit changes weekly for one approved sensor type. What do you configure, validate, and regression-test?", competencyWeights: { api: 1, dataInterfaces: .8, testingDebugging: .9, architecture: .6, defense: .8 } },
  { id: "interview-incident-draft", title: "60-minute incident-summary draft", durationMinutes: 60, mode: "ai-boundary", prompt: "Build an API that accepts an unstructured fictional incident description, extracts key facts, and returns a draft summary for human review. Defend why AI is justified here and where trusted code must retain control.", guidedHint: "Use schema-first extraction, explicit uncertainty, validation, a human-review status, safe failure, and no autonomous ticketing or action.", followUp: "The model invents an owner not present in the source text. What does the response contain and what must not happen?", competencyWeights: { aiApplications: 1, api: .8, securityReliability: 1, testingDebugging: .7, defense: 1 } },
  { id: "interview-handoff-search", title: "90-minute handoff-search prototype", durationMinutes: 90, mode: "project-defense", prompt: "Another fictional department manually reviews shift handoff notes. Design a prototype that extracts blockers, owners, deadlines, and unresolved questions, then provides a searchable result. Choose in-memory storage or SQLite and defend the decision.", guidedHint: "Scope one vertical slice: typed input, bounded extraction, persistent or in-memory data choice, a search/filter contract, human review, and a small evaluation/test plan.", followUp: "The team asks for write-back to their workflow. What is the smallest safe next step, and who must be involved?", competencyWeights: { decomposition: 1, architecture: 1, dataInterfaces: .8, aiApplications: .8, securityReliability: .9, defense: 1 } },
  { id: "interview-triage-api", title: "Build the narrow triage API", durationMinutes: 12, mode: "architecture", prompt: "A fictional team manually reviews equipment readings. Describe a Python prototype that accepts a reading, returns NORMAL, REVIEW, or URGENT, and can be demonstrated in an interview.", guidedHint: "Begin with user outcome, then name input, request validation, pure rule, response, test, and what is intentionally out of scope.", followUp: "The interviewer now says the rule may change weekly. What would you make configurable, and what would you keep tested?", competencyWeights: { decomposition: 1, api: .8, testingDebugging: .7, defense: 1 } },
  { id: "interview-broken-api", title: "Recover a broken API", durationMinutes: 10, mode: "debug", prompt: "A clean test run reports ModuleNotFoundError for your app package. Walk the interviewer through your diagnostic path before proposing a repair.", guidedHint: "Use observation → hypothesis → smallest diagnostic → repair → regression evidence. Do not begin by reinstalling unrelated packages.", followUp: "The import now works locally but fails in CI. Which assumption would you inspect next?", competencyWeights: { testingDebugging: 1, terminal: .6, defense: .8 } },
  { id: "interview-ai-boundary", title: "Add AI without granting authority", durationMinutes: 12, mode: "ai-boundary", prompt: "A stakeholder asks for AI to read fictional maintenance notes and open operational tickets. Propose a safe first prototype and explain what the model may and may not do.", guidedHint: "Separate variable language extraction from trusted policy, tool permission, approval, audit evidence, and degraded mode.", followUp: "A retrieved note attempts to override your system instructions. What changes in the design?", competencyWeights: { aiApplications: 1, securityReliability: 1, defense: 1 } },
  { id: "interview-handoff-defense", title: "Defend the handoff assistant", durationMinutes: 15, mode: "project-defense", prompt: "Walk through the Mission Operations Handoff Assistant as if a skeptical engineer is reviewing your work. State what you designed, what AI assisted, tests you ran, failure behavior, and what you would change before a broader pilot.", guidedHint: "Own the decisions honestly. A prototype is valuable only when its boundary and evidence are clear.", followUp: "Show one specific thing you would rebuild without AI assistance to prove you maintain it.", competencyWeights: { defense: 1, git: .5, testingDebugging: .6, securityReliability: .7 } },
  { id: "interview-requirement-change", title: "Respond to the changing requirement", durationMinutes: 12, mode: "requirements-change", prompt: "Halfway through a prototype, a reviewer says each team must only see its own fictional handoff notes and asks for automatic write-back. Re-scope the design under time pressure.", guidedHint: "Clarify identity and data boundaries first. A smaller read-only or human-approved path may be the strongest response.", followUp: "What would make you decide no AI should be used in this workflow?", competencyWeights: { decomposition: .8, securityReliability: 1, architecture: .7, defense: 1 } },
];
