import type { Activity, AssessmentQuestion, CompetencyKey, InterviewQuestion, ProjectTemplate, TrackDefinition, TrackId } from "./types";

const weights: Record<CompetencyKey, number> = { foundations: 1, roleJudgment: 1.1, architecture: 1, security: 1.05, production: 1, leadership: .9, communication: 1, aiCollaboration: .75 };
const rubric = { criteria: [{ label: "Technical accuracy", weight: 35 }, { label: "Safe operating judgment", weight: 30 }, { label: "Clear reasoning", weight: 20 }, { label: "Evidence and ownership", weight: 15 }], minimumEvidence: ["State the user outcome or operating context", "Name a constraint or risk", "Recommend a test, verification, or escalation point"] };
const sharedPhases = [
  { id: "reality-check" as const, title: "Reality Check", duration: "45 min", summary: "Understand the work, constraints, and baseline gaps." },
  { id: "crash-course" as const, title: "48-Hour Crash Course", duration: "48 hours", summary: "Build immediate interview confidence and a defensible packet." },
];
const aioPhases = [
  ...sharedPhases,
  { id: "foundation-bridge" as const, title: "Zero-to-Role Foundation", duration: "6 weeks", summary: "Build Python and application-system confidence from zero knowledge." },
  { id: "fast-track" as const, title: "Applied AI Fast Track", duration: "8 weeks", summary: "Develop applied AI, system design, and technical-partner judgment." },
  { id: "master-track" as const, title: "Master Track", duration: "4 weeks", summary: "Build durable professional depth and a capstone." },
  { id: "interview-simulator" as const, title: "Interview Simulator", duration: "Ongoing", summary: "Practice pressure, technical depth, and project defense." }
];
const itPhases = [
  ...sharedPhases,
  { id: "fast-track" as const, title: "Fast Track", duration: "2–3 weeks", summary: "Develop job-ready fundamentals through active practice." },
  { id: "master-track" as const, title: "Master Track", duration: "8–12 weeks", summary: "Build durable professional depth and a capstone." },
  { id: "interview-simulator" as const, title: "Interview Simulator", duration: "Ongoing", summary: "Practice pressure, technical depth, and project defense." },
];

function assessment(track: TrackId, seed: Array<[string, string, string, string, string, CompetencyKey]>): AssessmentQuestion[] {
  if (seed.length !== 24) throw new Error(`${track} must define exactly 24 baseline questions.`);
  const optionOrders = [
    [0, 1, 2, 3],
    [1, 3, 0, 2],
    [2, 0, 3, 1],
    [3, 2, 1, 0],
    [1, 0, 2, 3],
    [2, 3, 1, 0],
    [3, 1, 0, 2],
    [0, 2, 3, 1],
  ] as const;
  return seed.map((item, index) => {
    // The source answer is always the first seeded choice so content remains
    // easy to review. Presentation order is deliberately varied and grading
    // follows the resulting index, never an assumed "A" answer.
    const order = optionOrders[(index * 3 + track.length) % optionOrders.length];
    return {
      id: `${track}-assessment-${index + 1}`,
      prompt: item[0],
      choices: order.map((choiceIndex) => item[choiceIndex + 1]),
      correct: order.indexOf(0),
      competency: item[5],
    };
  });
}
function activities(track: TrackId, input: Array<{ phaseId: Activity["phaseId"]; type: Activity["type"]; title: string; summary: string; pillar: string; mode?: string; prompt?: string; choices?: string[]; correctChoice?: number; competency: CompetencyKey; capstone?: boolean }>): Activity[] {
  return input.map((item, index) => ({ id: `${track}-${item.phaseId}-${index + 1}`, ...item, mode: item.mode as Activity["mode"], duration: item.phaseId === "crash-course" ? 35 : item.type === "lab" ? 30 : 25, objectives: ["Identify the operating context and key constraint.", "Make a safe, evidence-based recommendation.", "Explain how you would verify or escalate the result."], evidence: item.type === "lab" || item.type === "mission" ? "Record a safe decision and review the feedback." : "Write a concise, defensible response.", competencies: { [item.competency]: 1, communication: .35 }, rubric }));
}

const aiAssessmentSeed: Array<[string, string, string, string, string, CompetencyKey]> = [
  ["A team asks for an AI agent. What do you do first?", "Map the workflow, decision owner, constraints, and success measure.", "Define a narrow demo after the requesting team names a model preference.", "Prototype an assistant to discover what information users may need.", "Identify the data boundary before confirming the operational outcome.", "leadership"],
  ["What is the safest first release for sensitive internal procedures?", "Permission-aware, cited, read-only retrieval with human escalation.", "Cited retrieval that applies document permissions only after generation.", "A narrow human-approved workflow that can directly edit procedure records.", "Broad retrieval followed by prompt-based redaction of sensitive passages.", "security"],
  ["When is conventional automation usually better than an LLM?", "When rules are clear and deterministic output is required.", "When document language must be interpreted across inconsistent source formats.", "When an operator needs an explanation tailored to a changing situation.", "When the next step depends on ambiguous evidence and a human review loop.", "roleJudgment"],
  ["What makes RAG useful?", "It brings relevant authorized source context into the response flow.", "It turns retrieved documents into permanent model knowledge after one use.", "It replaces source authorization because retrieval occurs inside the system.", "It guarantees a response is correct whenever a citation is present.", "architecture"],
  ["How do you evaluate an AI workflow?", "Use representative cases, task metrics, human review, latency, and failure trends.", "Compare two polished demonstrations and collect stakeholder preference notes.", "Track model confidence and response length across a sample of prompts.", "Use a model grader alone to decide whether outputs are safe to deploy.", "production"],
  ["What is honest AI-native engineering?", "Use AI to accelerate, then review, test, explain, and own what ships.", "Use generated output for low-risk changes and treat compilation as sufficient review.", "Use AI for ideation only, even when it could improve a careful engineering workflow.", "Present AI-assisted output as independent work so the project appears more complete.", "aiCollaboration"],
  ["Why are embeddings used in retrieval?", "They help compare semantic similarity between a query and authorized content.", "They assign a user’s authorization level before a document can be retrieved.", "They make retrieved text immutable after it enters the knowledge index.", "They replace citations by proving that a response came from internal data.", "architecture"],
  ["A RAG assistant returns irrelevant passages. What is a sound next investigation?", "Inspect query intent, chunking, metadata filters, retrieval results, and reranking.", "Increase response creativity so the model can infer the missing connection.", "Expand retrieval access first, then assess whether relevance improves for the user.", "Add another tool before inspecting the documents and ranking behavior already in use.", "production"],
  ["What is an indirect prompt-injection risk?", "Retrieved content tries to override the system’s instructions or trigger unsafe tool use.", "A user asks a model to summarize a source that contains conflicting information.", "A model receives a request with too little context to answer confidently.", "A knowledge source returns a passage that is outdated but otherwise trustworthy.", "security"],
  ["How should a production AI service handle structured output?", "Validate against a schema and fail safely when the response is invalid.", "Prompt for valid JSON and send the response through when it appears parseable.", "Use a second model to rewrite malformed fields without retaining the original response.", "Accept optional fields from the model and leave downstream services to reject unsafe cases.", "foundations"],
  ["What is the right default for a new tool-connected assistant?", "Give it the least privilege needed and require approval before consequential actions.", "Give it temporary write access in a pilot so the team can evaluate end-to-end value.", "Let the model request additional permissions when a user asks for a blocked action.", "Grant access to the supporting system and rely on audit logs to catch inappropriate use.", "security"],
  ["What does a golden evaluation set provide?", "Representative expected cases that make quality changes measurable over time.", "A curated set of difficult prompts used only before the first product demonstration.", "A source library that the assistant can retrieve whenever a question is unclear.", "A model-specific benchmark that removes the need for task-level human evaluation.", "production"],
  ["A system passes a demo but fails a critical edge case. What should happen?", "Add the case to evaluation, classify the failure, fix safely, and run regression tests.", "Document the exception, keep it outside the benchmark, and monitor the next release closely.", "Increase the context budget, then repeat the demo that originally passed without changes.", "Use a human reviewer for that single case while retaining the existing release criteria.", "production"],
  ["Which concern belongs in model selection?", "Quality, latency, cost, context needs, approved deployment boundary, and reliability.", "Benchmark quality, total parameters, and whether the provider offers a familiar chat interface.", "Token price, model popularity, and the amount of prompt engineering already invested.", "Context window, public leaderboard ranking, and whether a team already has an account.", "architecture"],
  ["Why should authorization occur before retrieval?", "The system should never fetch context the user is not allowed to see.", "The model needs a complete set of candidate documents before it can filter sensitive material.", "Authorization can occur after generation as long as the final response redacts restricted terms.", "Retrieval access may be broad if only approved users are allowed to ask the assistant questions.", "security"],
  ["What is idempotency protecting in a tool workflow?", "A retry cannot accidentally repeat a consequential action.", "A model retry returns the same explanation so users receive consistent language.", "A delayed UI request redraws the original form without showing a duplicate field.", "A document-ingestion job always indexes the same number of chunks after a change.", "foundations"],
  ["A model provider is unavailable. What is a production-ready response?", "Fail visibly, preserve the request safely, use an approved fallback if available, and communicate status.", "Retry the request in the browser until a response returns, then show the original timestamp.", "Return a best-effort answer from cached context even when no approved model call succeeds.", "Expose an alternate provider endpoint to users so they can choose their own fallback.", "production"],
  ["A stakeholder says, ‘We need AI.’ What is the strongest response?", "Clarify the workflow and success criteria, then compare AI with automation, search, or process change.", "Identify the best available model, then ask the team to propose tasks it could automate.", "Build a short agent prototype and use early reactions to determine the underlying problem.", "Start collecting training examples so the organization has options when the use case becomes clear.", "leadership"],
  ["What makes an architecture explanation credible in an interview?", "State the user outcome, components, boundaries, tradeoffs, evaluation, and failure handling.", "Name the model, database, and framework, then explain how each component is technically current.", "Begin with the front end because it is closest to the user, then cover infrastructure if asked.", "Focus on the ideal system flow and reserve risk, monitoring, and approval details for implementation.", "communication"],
  ["When reviewing AI-generated code, what is your responsibility?", "Verify behavior, security, tests, error handling, and your ability to maintain it.", "Run the generated test suite, then merge if the proposed change does not create a compilation error.", "Ask the model to explain its implementation, then rely on that explanation for change approval.", "Rewrite the implementation by hand to demonstrate ownership even when the generated design is sound.", "aiCollaboration"],
  ["What should an audit event make possible?", "Trace who requested or approved an action, what data/path was used, and what outcome occurred.", "Capture the complete user prompt and source corpus so future reviewers can reconstruct every token.", "Record successful actions and model version details while excluding failed attempts from the evidence trail.", "Store the final action payload centrally so access controls can be inferred after an incident occurs.", "security"],
  ["A team wants an autonomous system to modify operational records. What is a prudent first step?", "Pilot a read-only or human-approved workflow with explicit rollback and evaluation.", "Scope autonomous write access to a small user group and rely on prompts to prevent unexpected actions.", "Use a second model to review proposed changes, then allow the first model to execute approved patterns.", "Automate a reversible record update first, then add approval when enough activity data has been collected.", "roleJudgment"],
  ["What does healthy AI collaboration look like during a production incident?", "Use AI for bounded analysis if permitted, while independently validating evidence and owning the recovery.", "Use an AI-generated remediation plan after a teammate reviews the prompt and confirms the model is current.", "Wait for the preferred AI tool to become available rather than switching to an unfamiliar diagnostic path.", "Let the model propose and execute a temporary recovery action when the user impact is high enough.", "aiCollaboration"],
  ["Why monitor cost and latency alongside answer quality?", "A useful system must remain reliable and viable under real demand, not only correct in isolation.", "They indicate whether a model has enough capability to replace human review in high-risk workflows.", "They determine how much source context should be retrieved, regardless of task requirements or security.", "They matter mainly after launch because early pilots should optimize for answer quality above all else.", "architecture"]
];
const itAssessmentSeed: Array<[string, string, string, string, string, CompetencyKey]> = [
  ["An engineer’s workstation fails before a critical test. What is your first move?", "Confirm impact, preserve evidence, use a known-good recovery path, and communicate the next checkpoint.", "Reinstall Windows immediately.", "Try random fixes until it works.", "Wait for a senior technician without updating the user.", "production"],
  ["A device has an IP address but cannot reach an internal hostname. What should you test?", "DNS resolution, assigned DNS servers, name-versus-IP behavior, and issue scope.", "Replace the monitor cable.", "Reset every network switch.", "Change the user’s password.", "foundations"],
  ["What is the safe initial response to a production device needing network access?", "Collect device requirements and coordinate authorized port/VLAN ownership.", "Plug it into any open network port.", "Assign a static address without approval.", "Ask the user to bypass security.", "security"],
  ["A shared label printer is online but jobs remain queued. What is the process?", "Check queue, driver, print path/port, scope, test print, and device state.", "Delete every printer driver first.", "Restart the entire network.", "Tell users to print elsewhere without investigation.", "roleJudgment"],
  ["Three urgent requests arrive simultaneously. What do you do?", "Triage impact and urgency, acknowledge each, communicate ownership, and escalate as appropriate.", "Solve the loudest request first.", "Ignore lower-ranked users.", "Close all tickets and restart later.", "leadership"],
  ["An AI tool suggests a registry edit. What must happen before using it?", "Confirm applicability, test safely, prepare rollback, follow policy, and document the result.", "Apply it because the AI is confident.", "Send it to every endpoint.", "Ignore all tools permanently.", "aiCollaboration"],
  ["A device receives a 169.254.x.x address. What does that usually suggest?", "It could not obtain a DHCP lease, so inspect link, VLAN, DHCP reachability, and scope.", "DNS is resolving correctly.", "The printer driver is corrupt.", "The user has too much local storage.", "foundations"],
  ["A user can reach an IP address but not an application name. What is the most likely layer to inspect first?", "DNS configuration and name resolution.", "The monitor cable.", "The asset tag.", "The keyboard layout.", "foundations"],
  ["What is a safe reason to escalate a VLAN or switch-port request?", "Network ownership must validate device identity, segmentation, and the approved network path.", "Any user prefers a different IP address.", "A device needs faster Wi-Fi.", "A printer has an empty tray.", "security"],
  ["What protects a lost laptop’s local data?", "Managed encryption, recovery-key controls, asset tracking, and an approved remote-response process.", "A desktop wallpaper warning.", "A shared local administrator password.", "Deleting the user’s profile.", "security"],
  ["A new dock powers a laptop but external displays are blank. What is a sound first check?", "Confirm dock compatibility, power, cable/display input, driver/firmware state, and isolate with known-good hardware.", "Immediately reimage the laptop.", "Change the user’s password.", "Reset every network switch.", "roleJudgment"],
  ["Where can you begin investigating a repeat Windows application crash?", "Event Viewer, application logs, recent changes, error codes, and whether the issue reproduces for another user/device.", "The recycle bin only.", "The printer queue only.", "A random registry cleanup tool.", "production"],
  ["What is the difference between identity authentication and authorization?", "Authentication verifies who a user is; authorization controls what that verified user may access.", "They are two names for password reset.", "Authorization verifies hardware serial numbers.", "Authentication assigns VLANs.", "foundations"],
  ["A user cannot pass MFA after a phone replacement. What is the safest next move?", "Verify identity through the approved process, then reset/re-register the factor and confirm access.", "Disable MFA permanently.", "Ask them to use someone else’s device.", "Send a code over an unverified channel.", "security"],
  ["A Teams call has no audio in one conference room. What is a structured troubleshooting path?", "Check scope, room power, selected input/output devices, cabling, application settings, test call, and known-good fallback.", "Reinstall every employee’s Teams client.", "Change the room VLAN without evidence.", "Delete the meeting invite.", "roleJudgment"],
  ["A Zebra label printer prints blank labels. What should you inspect before broad changes?", "Correct media/ribbon, calibration, print language/settings, driver, queue, and a controlled test label.", "Reset all print servers.", "Replace every workstation.", "Turn off logging.", "production"],
  ["What is an appropriate first response to an MFP scanning failure?", "Confirm scope, device status, destination/path permissions, network reachability, and test with an approved account.", "Change all users’ email passwords.", "Factory reset it without checking settings.", "Assume the scanner hardware is dead.", "roleJudgment"],
  ["A macOS user cannot open an approved app after an update. What should you check?", "Application compatibility, permissions/security prompts, device management state, logs, and whether it affects other managed Macs.", "Use a Windows registry cleaner.", "Join it to an unknown Wi-Fi network.", "Remove all endpoint controls.", "foundations"],
  ["A Linux service is unavailable after restart. Which evidence is most useful?", "Service status and journal logs, configuration changes, dependencies, and port/process state.", "Only the desktop wallpaper.", "The Windows recycle bin.", "The printer’s toner level.", "production"],
  ["What should happen before issuing a replacement mobile device?", "Confirm identity and approval, protect or wipe the prior device as policy allows, enroll the replacement, verify access, and update asset records.", "Hand out any phone without recording it.", "Copy credentials through text messages.", "Remove device management to speed setup.", "security"],
  ["Why does accurate asset lifecycle data matter?", "It supports secure deployment, support history, recovery, warranty, audits, and timely retirement.", "It only makes storage shelves look organized.", "It replaces endpoint encryption.", "It eliminates user support.", "leadership"],
  ["What should a good incident update tell the affected engineer?", "Impact, current action, expected checkpoint, any safe workaround, and when you will update again.", "Every internal troubleshooting theory.", "Nothing until the issue is solved.", "That they caused the problem.", "communication"],
  ["When documenting a repeat fix, what makes it a useful runbook?", "Clear scope, prerequisites, ordered safe steps, verification, rollback/escalation criteria, and ownership.", "A long list of unrelated links.", "Only a screenshot of success.", "Instructions that require guessing.", "communication"],
  ["A workstation’s Ethernet link is down after a desk move. What is a safe first path?", "Check physical link, known-good cable/port, adapter state, assigned network settings, and scope before escalation.", "Assign a random static address.", "Reset every switch in the building.", "Reimage the workstation immediately.", "foundations"]
];

const aiInput = [
  { phaseId: "reality-check" as const, type: "lesson" as const, title: "Applied AI operating reality", summary: "Frame the role as technical partner, builder, and safe adopter—not an AI salesperson.", pillar: "Role judgment", competency: "roleJudgment" as const, prompt: "Explain when you would recommend no AI at all." },
  { phaseId: "crash-course" as const, type: "drill" as const, title: "Role narrative", summary: "Position your operations, product, and engineering strengths credibly.", pillar: "Interview", competency: "communication" as const, prompt: "Why are you a strong fit for an Applied AI Operations role?" },
  { phaseId: "crash-course" as const, type: "lesson" as const, title: "RAG, tools, and evaluation", summary: "Explain the practical building blocks of trustworthy LLM systems.", pillar: "Applied AI", competency: "architecture" as const, prompt: "Explain a permission-aware document assistant in plain language." },
  { phaseId: "crash-course" as const, type: "mission" as const, title: "Secure AI boundary", summary: "Choose a narrow, controlled pilot for a high-trust environment.", pillar: "Enterprise AI", competency: "security" as const, mode: "Solo", choices: ["Read-only retrieval with citations, access controls, human escalation, and evaluation.", "Autonomous write access with logging.", "A public chatbot that copies all documents."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lesson" as const, title: "Python service foundations", summary: "APIs, validation, data flow, logging, and testing.", pillar: "Software", competency: "foundations" as const, prompt: "Describe an API boundary you would trust in production." },
  { phaseId: "fast-track" as const, type: "lesson" as const, title: "Rust systems fundamentals", summary: "Ownership, errors, modules, and disciplined implementation.", pillar: "Software", competency: "foundations" as const, prompt: "Explain when Rust makes a systems component safer to maintain." },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "Structured output review", summary: "Turn an AI-generated summarizer into a predictable interface.", pillar: "Applied AI", competency: "aiCollaboration" as const, mode: "Pair Programming", choices: ["Define a schema, validate it, and handle validation failures explicitly.", "Parse prose with string splitting.", "Increase temperature until it looks like JSON."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "Permission-aware retrieval", summary: "Review AI-generated RAG code for access-control failures.", pillar: "Enterprise AI", competency: "security" as const, mode: "AI Builder", choices: ["Filter permissions before retrieval and return source citations.", "Retrieve everything then ask the model to hide secrets.", "Use a larger embedding model for authorization."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "AI outage incident", summary: "Recover from duplicate tool execution with no copilot available.", pillar: "Production", competency: "production" as const, mode: "Production Incident", choices: ["Contain writes, inspect idempotency and logs, correct state, then add regression coverage.", "Retry the agent until it stops duplicating actions.", "Turn off logs to reduce noise."], correctChoice: 0 },
  { phaseId: "master-track" as const, type: "mission" as const, title: "Applied AI Operations Capstone", summary: "Design a measurable rollout with observability, rollback, and governance.", pillar: "Systems", competency: "architecture" as const, mode: "Solo", capstone: true, prompt: "Propose a phased rollout plan for a grounded enterprise assistant." },
  { phaseId: "master-track" as const, type: "lesson" as const, title: "Observability and reliability", summary: "Trace model, retrieval, tool, cost, latency, and safety failures.", pillar: "Production", competency: "production" as const, prompt: "Name the signals that tell you the AI workflow is drifting." },
  { phaseId: "interview-simulator" as const, type: "interview" as const, title: "Applied AI system design", summary: "Defend an enterprise assistant from discovery through controlled production.", pillar: "Interview", competency: "communication" as const, prompt: "Design an assistant that helps engineers investigate anomalies using authorized procedures and incident summaries." }
];
const itInput = [
  { phaseId: "reality-check" as const, type: "lesson" as const, title: "Mission-critical service reality", summary: "Support engineering and operations without unsafe improvisation.", pillar: "Service", competency: "roleJudgment" as const, prompt: "Explain how enterprise support differs from fixing a home computer." },
  { phaseId: "crash-course" as const, type: "drill" as const, title: "Hardware and Windows essentials", summary: "Boot sequence, storage, docks, displays, drivers, Event Viewer, services, and safe swaps.", pillar: "Endpoint", competency: "foundations" as const, prompt: "Walk through a workstation that powers on but does not boot Windows." },
  { phaseId: "crash-course" as const, type: "drill" as const, title: "Network support essentials", summary: "IP, DHCP, DNS, gateway, VLANs, ping, tracert, ipconfig, and nslookup.", pillar: "Networking", competency: "foundations" as const, prompt: "Why could DNS fail while the network still appears connected?" },
  { phaseId: "crash-course" as const, type: "drill" as const, title: "Microsoft, printing, and service", summary: "MFA, account support, queues, drivers, label printers, and calm communication.", pillar: "Enterprise IT", competency: "communication" as const, prompt: "Explain how you would handle three urgent tickets at once." },
  { phaseId: "fast-track" as const, type: "lesson" as const, title: "Enterprise Windows administration", summary: "Profiles, updates, encryption, drivers, logs, and repair decisions.", pillar: "Endpoint", competency: "foundations" as const, prompt: "Describe your safe process for a corrupted Windows profile." },
  { phaseId: "fast-track" as const, type: "lesson" as const, title: "Networking for IT support", summary: "Connectivity layers, port/VLAN boundaries, Wi-Fi, cabling, and escalation.", pillar: "Networking", competency: "architecture" as const, prompt: "What evidence do you gather before requesting a VLAN change?" },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "Printer path triage", summary: "Diagnose a queue, driver, port, server, or device failure.", pillar: "Printing", competency: "roleJudgment" as const, mode: "Solo", choices: ["Confirm scope, queue, driver, port/path, test page, and device state.", "Delete all drivers immediately.", "Restart every network device."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "PowerShell inventory review", summary: "Use Kyra as a reviewer without surrendering ownership.", pillar: "Automation", competency: "aiCollaboration" as const, mode: "Pair Programming", choices: ["Review inputs, permissions, output, error handling, and rollback before use.", "Run the script against every device first.", "Trust output because it is automated."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "AI-generated printer fix", summary: "Reject unsafe configuration advice and select a verified recovery path.", pillar: "Printing", competency: "security" as const, mode: "AI Builder", choices: ["Validate the queue and driver path in a safe scope before any change.", "Apply a registry edit to all endpoints.", "Disable security software to test faster."], correctChoice: 0 },
  { phaseId: "fast-track" as const, type: "lab" as const, title: "Critical incident without copilot", summary: "A generated workflow duplicated an account action. Recover safely.", pillar: "Operations", competency: "production" as const, mode: "Production Incident", choices: ["Contain impact, inspect audit records, correct state, and add prevention.", "Retry the workflow repeatedly.", "Delete the logs."], correctChoice: 0 },
  { phaseId: "master-track" as const, type: "mission" as const, title: "Production device onboarding", summary: "Connect a non-traditional device while honoring network ownership and security boundaries.", pillar: "Networking", competency: "security" as const, mode: "Solo", prompt: "Outline a safe onboarding plan for a test device that needs network access." },
  { phaseId: "master-track" as const, type: "mission" as const, title: "Mission Control Endpoint Readiness", summary: "Build a support program spanning lifecycle, incident runbooks, automation, and metrics.", pillar: "Capstone", competency: "leadership" as const, mode: "Solo", capstone: true, prompt: "Present the operating plan you would use to improve endpoint readiness in a critical facility." },
  { phaseId: "interview-simulator" as const, type: "interview" as const, title: "Pressure support simulation", summary: "Prioritize and communicate through a workstation, printer, and conference-room outage.", pillar: "Interview", competency: "communication" as const, prompt: "Three high-priority issues arrive during a critical operation. How do you triage, communicate, and escalate?" }
];

const aiProjects: ProjectTemplate[] = [
  { id: "ai-procedure", title: "Permission-Aware Procedure Assistant", problem: "Engineers need trustworthy answers from fragmented sensitive procedure libraries.", constraints: "Synthetic data only; role-based access; citations; read-only pilot.", architecture: "Authenticated UI → policy filter → retrieval → grounded response → citation panel → audit event.", success: "Grounded-answer rate, retrieval relevance, unauthorized-access failures, latency, and reviewer acceptance.", defense: "Why does authorization happen before retrieval rather than in the prompt?", repositoryPath: "prototypes/permission-aware-knowledge-assistant", requiredEvidence: ["Run the authorization, stale-source, conflict, and unsupported-answer tests.", "Complete the deliberate authorization-order failure exercise and record the repair.", "Save one trace showing citations or a justified abstention.", "Disclose your AI assistance and what you independently verified."] },
  { id: "ai-workflow", title: "Human-Approved Operations Workflow", problem: "A repetitive operational workflow needs assistance without surrendering decision authority.", constraints: "No autonomous side effects; qualified approval; audit history; reversible rollout.", architecture: "Intake → structured classification → retrieval → action draft → approval → scoped tool → audit.", success: "Task completion, approval rejection rate, duplicate-action prevention, and escalation quality.", defense: "Where does automation stop, and why?", repositoryPath: "prototypes/human-approved-operations-triage", requiredEvidence: ["Run the approval, critical-escalation, and idempotency tests.", "Complete the deliberate unapproved-execution failure exercise and repair it.", "Save a fictional audit trace proving one approved action executed once.", "Disclose your AI assistance and the checks you personally performed."] }
];
const itProjects: ProjectTemplate[] = [
  { id: "it-lifecycle", title: "Endpoint Lifecycle Improvement", problem: "Inconsistent replacements create user downtime and incomplete asset records.", constraints: "Traceability, approved tooling, encryption, recovery, and fictional data.", architecture: "Receive → tag → record → configure → validate → deploy → recover → retire → audit.", success: "Deployment time, first-week incident rate, asset completeness, and recovery compliance.", defense: "Which steps protect security versus convenience, and what breaks when one is skipped?" },
  { id: "it-runbook", title: "Critical Operations Support Runbook", problem: "High-urgency endpoint, printing, and meeting-room incidents lack a consistent response path.", constraints: "Time pressure, controlled change, escalation boundaries, evidence preservation.", architecture: "Intake → impact triage → containment → known-good fallback → diagnostics → escalation → verification → documentation.", success: "Time to acknowledge, safe restoration, escalation accuracy, and repeat-incident reduction.", defense: "How do you distinguish a workaround from a reliable fix?" }
];
const aiQuestions: InterviewQuestion[] = ["Explain RAG to an engineer.", "How would you reduce hallucinations?", "When should you not use AI?", "Design a secure internal assistant.", "How do you evaluate model quality?", "Tell me about an AI-assisted project you can defend."].map((prompt, index) => ({ id: `ai-q-${index + 1}`, category: index < 4 ? "Technical" : "Project defense", prompt, why: "Tests practical judgment, not terminology recall.", answerShape: "State the user outcome, constraints, proposed boundary, evidence, and next tradeoff." }));
const itQuestions: InterviewQuestion[] = ["Walk me through a computer that will not boot.", "Why can DNS fail while networking appears connected?", "What is a VLAN and when do you escalate?", "How do you troubleshoot a printer with queued jobs?", "How do you prioritize several urgent requests?", "How do you support a demanding engineer under time pressure?"].map((prompt, index) => ({ id: `it-q-${index + 1}`, category: index < 4 ? "Technical" : "Behavioral", prompt, why: "Tests structured troubleshooting, safety, and customer communication.", answerShape: "Clarify impact, gather evidence, isolate safely, test, verify, communicate, and document." }));

export const crashCoursePlan: Record<TrackId, Array<{ day: "Day 1" | "Day 2"; time: string; title: string; focus: string; activityId?: string }>> = {
  "applied-ai-operations": [
    { day: "Day 1", time: "Hour 0–2", title: "Role narrative", focus: "Write the credible bridge between your operations, product, and technical strengths.", activityId: "applied-ai-operations-crash-course-2" },
    { day: "Day 1", time: "Hour 2–5", title: "LLM fundamentals", focus: "Explain models, prompts, structured outputs, tools, and limits without hype." },
    { day: "Day 1", time: "Hour 5–8", title: "RAG and evaluation", focus: "Practice retrieval, grounding, citations, failure modes, and success measures.", activityId: "applied-ai-operations-crash-course-3" },
    { day: "Day 1", time: "Hour 8–10", title: "Secure boundary", focus: "Choose what data, permissions, human approvals, and operating limits belong in the pilot.", activityId: "applied-ai-operations-crash-course-4" },
    { day: "Day 2", time: "Hour 24–27", title: "System design", focus: "Draw an authorized assistant from identity through retrieval, model, audit, and escalation." },
    { day: "Day 2", time: "Hour 27–30", title: "Project packaging", focus: "Turn two projects into honest, measurable case studies with your contribution and lessons." },
    { day: "Day 2", time: "Hour 30–33", title: "Pressure stories", focus: "Practice ownership, skeptical stakeholders, unsafe requests, and fast delivery with STAR structure." },
    { day: "Day 2", time: "Hour 33–36", title: "Full mock loop", focus: "Run rapid technical, system design, and project-defense questions; revise your packet." }
  ],
  "it-support-technician": [
    { day: "Day 1", time: "Hour 0–2", title: "Hardware and Windows", focus: "Review boot flow, storage, docks, displays, Device Manager, Event Viewer, and known-good swaps.", activityId: "it-support-technician-crash-course-2" },
    { day: "Day 1", time: "Hour 2–5", title: "Networking essentials", focus: "Practice IP, DHCP, DNS, gateway, VLAN, ping, tracert, ipconfig, and nslookup.", activityId: "it-support-technician-crash-course-3" },
    { day: "Day 1", time: "Hour 5–8", title: "Troubleshooting method", focus: "Repeat observe, scope, gather evidence, isolate, test, verify, document, and communicate." },
    { day: "Day 1", time: "Hour 8–10", title: "Mission-critical response", focus: "Prioritize impact, preserve evidence, use safe recovery paths, and keep the user updated." },
    { day: "Day 2", time: "Hour 24–27", title: "Microsoft and identity", focus: "Review Entra/AD concepts, MFA recovery, encryption, managed devices, and access boundaries." },
    { day: "Day 2", time: "Hour 27–30", title: "Printing, mobile, and AV", focus: "Work queues, drivers, label printers, MFPs, device enrollment, and conference-room triage.", activityId: "it-support-technician-crash-course-4" },
    { day: "Day 2", time: "Hour 30–33", title: "Service stories", focus: "Prepare concise examples for interruptions, demanding users, escalation, documentation, and ownership." },
    { day: "Day 2", time: "Hour 33–36", title: "Full mock loop", focus: "Answer rapid technical and behavioral prompts; improve communication and decision order." }
  ]
};

function expansion(trackId: TrackId, phaseId: Activity["phaseId"], type: Activity["type"], topics: string[], competency: CompetencyKey, mode?: Activity["mode"]): Activity[] {
  return topics.map((title, index) => ({ id: `${trackId}-${phaseId}-${type}-exp-${index + 1}`, phaseId, type, title, summary: `Interactive ${type} focused on ${title.toLowerCase()}, safe operating boundaries, and interview-ready explanation.`, duration: type === "lab" || type === "mission" ? 30 : 25, pillar: phaseId === "master-track" ? "Mastery" : "Fast Track", objectives: ["Clarify the user or operational outcome.", "Identify the technical constraint and safe action.", "Verify the result and explain the tradeoff."], evidence: type === "lab" || type === "mission" ? "Record and defend your operating decision." : "Write a concise, defensible takeaway.", competencies: { [competency]: 1, communication: .35 }, rubric, mode }));
}
function questionBank(prefix: string, seed: InterviewQuestion[], total: number, technicalCount: number): InterviewQuestion[] {
  return Array.from({ length: total }, (_, index) => { const base = seed[index % seed.length]; return { ...base, id: `${prefix}-q-${index + 1}`, category: index < technicalCount ? "Technical" : index < total - 15 ? "Scenario" : "Behavioral / project defense", prompt: index < seed.length ? base.prompt : `${base.prompt} — variation ${index + 1}: state the assumptions, operating risk, and verification point.`, why: base.why, answerShape: base.answerShape }; });
}

const aiExtraLessons = expansion("applied-ai-operations", "fast-track", "lesson", ["API contracts and schema validation", "SQL and relational data", "Authentication and authorization", "Git, change review, and testing", "Prompt hierarchy and context construction", "Embeddings and hybrid retrieval", "Chunking, metadata, and reranking", "Tool calling and deterministic workflows", "Agent state, timeouts, and retries", "Evaluation datasets and regression testing", "Model selection, cost, and latency", "Observability and prompt/model versioning", "Caching, queues, and background jobs", "Docker and deployment fundamentals", "Stakeholder discovery and workflow mapping", "Technical decision records", "Risk registers and approval mapping", "Explaining AI to engineers and leaders", "Python async and error handling", "Rust ownership and result types"], "foundations");
const aiExtraLabs = expansion("applied-ai-operations", "fast-track", "lab", ["Prompt injection review", "Citation grounding check", "Golden dataset design", "Model-change regression", "Tool permission audit", "RAG relevance failure", "Stale-document conflict", "Output schema failure", "Latency and fallback analysis", "Cost-control decision", "Human approval gate", "Audit-log reconstruction", "Model outage recovery", "Async request diagnosis", "API error handling", "Database access review", "Feature-flag rollback"], "production", "Solo").map((item, index) => ({ ...item, mode: (["Solo", "Pair Programming", "AI Builder", "Production Incident"] as const)[index % 4] }));
const aiExtraMissions = expansion("applied-ai-operations", "master-track", "mission", ["Skeptical engineering-team discovery", "Conflicting procedure investigation", "Restricted-data pilot proposal", "Prototype-to-production design", "AI safety red-team review", "Enterprise evaluation recovery", "Multi-team priority conflict", "Executive implementation proposal"], "leadership", "Solo");
const itFastLessons = expansion("it-support-technician", "fast-track", "lesson", ["Hardware diagnostics and safe replacement", "Active Directory and Entra concepts", "Microsoft 365 service support", "Enterprise printing systems", "macOS support fundamentals", "Linux support fundamentals", "Mobile device management", "Audio visual and conference rooms", "IT asset lifecycle management", "PowerShell and safe automation", "Documentation and knowledge-base writing", "Customer service excellence", "Mission-critical IT operations"], "foundations");
const itMasterLessons = expansion("it-support-technician", "master-track", "lesson", ["Windows internals and profile recovery", "Windows imaging and deployment", "Autopilot and managed provisioning", "MECM/SCCM concepts", "Endpoint encryption and recovery", "Enterprise Wi-Fi and 802.1X concepts", "Switching, patch panels, and PoE", "Fiber and cabling basics", "Microsoft Intune device compliance", "Exchange Online and Teams support", "OneDrive, SharePoint, and permissions", "Enterprise label and thermal printing", "MFP troubleshooting and print servers", "Conference-room signal paths", "iOS and Android enrollment", "Linux package, service, and log support", "SSH and remote troubleshooting", "Inventory audits and asset recovery", "Procurement, warranty, and e-waste", "Backup and disaster-recovery concepts", "Endpoint security and least privilege", "PowerShell reporting automation", "Bash and Python support automation", "Service metrics and continual improvement"], "architecture");
const itExtraLabs = expansion("it-support-technician", "fast-track", "lab", ["Boot and BIOS/UEFI triage", "SSD failure and recovery path", "Dock, display, and USB-C diagnosis", "Device Manager driver review", "Event Viewer incident evidence", "DHCP and gateway triage", "DNS name-resolution failure", "Wi-Fi and cabling isolation", "VLAN escalation packet", "MFA and account-access triage", "Windows Update failure", "BitLocker recovery communication", "Network printer port diagnosis", "Zebra label calibration", "MFP scan-to-email failure", "macOS permission issue", "Linux systemctl and journalctl review", "Mobile enrollment failure", "Conference-room audio issue", "Asset-tag discrepancy", "PowerShell error review", "User profile recovery", "VPN connectivity boundary", "Remote support session hygiene", "Critical ticket status update", "Known-good device swap", "Warranty and repair routing"], "production", "Solo").map((item, index) => ({ ...item, mode: (["Solo", "Pair Programming", "AI Builder", "Production Incident"] as const)[index % 4] }));
const itExtraMissions = expansion("it-support-technician", "master-track", "mission", ["Critical workstation recovery", "Label-printing outage", "Conference-room preflight failure", "Asset-lifecycle discrepancy", "Skeptical engineer support", "Account lockout during operation", "Intermittent production-device connectivity", "Endpoint deployment rollback", "Executive AV support", "After-hours incident handoff"], "leadership", "Solo");

export const tracks: Record<TrackId, TrackDefinition> = {
  "applied-ai-operations": { id: "applied-ai-operations", title: "Applied AI Operations Engineer", subtitle: "AI-native systems, enterprise judgment, and technical leadership", price: "$349", accent: "teal", roleSummary: "Become the engineer who can discover a problem, design a controlled AI solution, build or guide a prototype, evaluate it, and defend the result.", competencyWeights: weights, assessment: [], phases: aioPhases, activities: [...activities("applied-ai-operations", aiInput), ...aiExtraLessons, ...aiExtraLabs, ...aiExtraMissions], projects: aiProjects, interviewQuestions: questionBank("ai", aiQuestions, 150, 100) },
  "it-support-technician": { id: "it-support-technician", title: "IT Support Technician", subtitle: "Mission-critical enterprise endpoint and service operations", price: "$249", accent: "amber", roleSummary: "Become the technician who can restore users safely, troubleshoot systems methodically, manage assets, and communicate calmly under operational pressure.", competencyWeights: weights, assessment: assessment("it-support-technician", itAssessmentSeed), phases: itPhases, activities: [...activities("it-support-technician", itInput), ...itFastLessons, ...itMasterLessons, ...itExtraLabs, ...itExtraMissions], projects: itProjects, interviewQuestions: questionBank("it", itQuestions, 150, 100) }
};
export const trackList = Object.values(tracks);
export const competencyLabels: Record<CompetencyKey, string> = { foundations: "Foundations", roleJudgment: "Role judgment", architecture: "Systems design", security: "Safe operations", production: "Troubleshooting", leadership: "Ownership", communication: "Communication", aiCollaboration: "AI collaboration" };
